#pragma once
#include <iostream>
#include <Windows.h>
#include <math.h>
#include <conio.h>
#include <algorithm>
#include <chrono>
#include <vector>
#include <stack>
#include <list>
#include <typeinfo>
using namespace std;

#include "Exeptions.h"
#include "FPS.h"
#include "DynamicArray.h"
#include "Map.h"
#include "GameObject.h"
#include "GameSpace.h"
#include "Item.h"
#include "Entity.h"
#include "Bilding.h"
#include "Door.h"
#include "CircDoor.h"
#include "RombDoor.h"
#include "TrianDoor.h"
#include "Trap.h"
#include "WeakTrap.h"
#include "MediumTrap.h"
#include "StrongTrap.h"
#include "Circle.h"
#include "Rectangle.h"
#include "Triangle.h"
#include "Rhombus.h"
#include "MedKit.h"
#include "Player.h"
#include "ConsoleBufferString.h"
